image: amazoncorretto:8

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - gradle

build:
  stage: build
  script:
    - ./gradlew build

after_script: