image: openjdk:8

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update && apt-get install -y openjfx

cache:
  paths:
    - gradle

build:
  stage: build
  script:
    - ./gradlew build

after_script: