package ass32gc

import it.unibo.pcd1819.mapmonitoring.guardian.GuardianActor
import it.unibo.pcd1819.mapmonitoring.model.NetworkConstants._
import it.unibo.pcd1819.mapmonitoring.sensor.SensorAgent
import it.unibo.pcd1819.mapmonitoring.view.DashboardActor

object Launcher extends App {
  SensorAgent.main(Seq(firstSeedPort.toString).toArray)
  GuardianActor.main(Seq(secondSeedPort.toString, "A").toArray)
  DashboardActor.main(Seq(thirdSeedPort.toString).toArray)

  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)
  GuardianActor.main(Seq("0", "A").toArray)

  SensorAgent.main(Seq(5500.toString).toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)
//  SensorAgent.main(Seq.empty.toArray)

//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//  GuardianActor.main(Seq("0", "B").toArray)
//
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//  GuardianActor.main(Seq("0", "C").toArray)
//
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//  GuardianActor.main(Seq("0", "D").toArray)
//
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)
//  GuardianActor.main(Seq("0", "E").toArray)

}